### ISSUE TITLE
Crash on in-use rack block removal

### ISSUE THREAD

**Issue by isthisrad** [Globox1997/FleshZ#3]
[crash-2021-11-01_07.20.25-client.txt](https://github.com/Globox1997/FleshZ/files/7453178/crash-2021-11-01_07.20.25-client.txt)

Game crashes upon removal of the block a rack is placed on while drying an item. After reloading the world, rack and item are on the ground in item form as expected.

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/FleshZ/commit/f3dd98206fae0eba10dfdb003289fd409949112f](https://github.com/Globox1997/FleshZ/commit/f3dd98206fae0eba10dfdb003289fd409949112f) and [https://github.com/Globox1997/FleshZ/commit/7449beaf166d314bfc48c8021e7ec9eef8ae9958](https://github.com/Globox1997/FleshZ/commit/7449beaf166d314bfc48c8021e7ec9eef8ae9958)
